'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useState } from 'react'

const css = `.status-shell{min-height:100vh;background:#071c16;color:#f0f8f4;display:grid;place-items:center;padding:32px}.status-card{width:min(680px,100%);text-align:center}.status-logo{position:fixed;top:26px;left:32px;color:#f0f8f4;text-decoration:none;font-family:var(--font-syne),sans-serif;font-weight:850}.status-logo span{color:#59d9a6}.orb{width:92px;height:92px;margin:0 auto 30px;border-radius:30px;background:radial-gradient(circle at 30% 25%,#7df4c2,#17865d 52%,#0b3a2b);box-shadow:0 25px 70px #30d29235;animation:float 2.5s ease-in-out infinite}.status-card h1{font-family:var(--font-syne),sans-serif;font-size:clamp(2.3rem,7vw,4.4rem);line-height:1;letter-spacing:-.06em;margin:0 0 18px}.status-card>p{color:#a8c1b7;max-width:520px;margin:0 auto 34px}.progress{width:min(480px,100%);margin:auto;text-align:left;border:1px solid #ffffff1c;border-radius:20px;padding:14px 24px;background:#ffffff08}.progress div{display:flex;gap:12px;align-items:center;padding:13px 0;color:#a8c1b7;border-bottom:1px solid #ffffff12}.progress div:last-child{border:0}.progress .done{color:#7df4c2}.progress .active{color:#fff}.result{background:#f2f8f5;color:#092019;border-radius:26px;padding:32px;margin-top:30px}.result a.button{display:inline-block;margin-top:18px;background:#147d59;color:#fff;text-decoration:none;border-radius:999px;padding:14px 22px;font-weight:800}.result-url{font-size:.78rem;color:#5f736b;word-break:break-all}.support{color:#7df4c2}.error-orb{background:#b63c34;box-shadow:0 25px 70px #d74b4135;animation:none}@keyframes float{50%{transform:translateY(-8px) rotate(3deg)}}@media(prefers-reduced-motion:reduce){.orb{animation:none}}`
type Status = 'generating'|'completed'|'failed'

export default function GeneratingPage(){
  const {id}=useParams<{id:string}>();const[status,setStatus]=useState<Status>('generating');const[url,setUrl]=useState<string|null>(null);const[message,setMessage]=useState('')
  useEffect(()=>{const token=new URLSearchParams(window.location.search).get('token');if(!token){setStatus('failed');setMessage('De beveiligde statuslink ontbreekt. Open de link opnieuw vanuit je intake.');return}let stopped=false;let timeout:number
    async function poll(){if(stopped)return;try{const response=await fetch(`/api/generated?order_id=${encodeURIComponent(id)}&token=${encodeURIComponent(token!)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Status ophalen mislukt.');setStatus(data.status);setUrl(data.netlify_url);setMessage(data.message||'');if(data.status==='generating')timeout=window.setTimeout(poll,document.hidden?12000:4000)}catch(error){setMessage(error instanceof Error?error.message:'Status ophalen mislukt.');timeout=window.setTimeout(poll,10000)}}poll();return()=>{stopped=true;window.clearTimeout(timeout)}},[id])
  const steps=['Betaling bevestigd','Briefing veilig ontvangen','Copy en ontwerp opbouwen','Pagina publiceren','Oplevering versturen']
  return <><style>{css}</style><main className="status-shell"><Link href="/" className="status-logo">landing<span>site</span>.nl</Link><div className="status-card">{status==='completed'?<><div className="orb"/><h1>Je eerste versie staat live.</h1><p>Bekijk de pagina op desktop én mobiel. Je ontvangt dezelfde link ook per e-mail.</p>{url&&<div className="result"><strong>Jouw beveiligde oplevering is afgerond</strong><p className="result-url">{url}</p><a className="button" href={url} target="_blank" rel="noopener noreferrer">Bekijk landingspagina</a></div>}</>:status==='failed'?<><div className="orb error-orb"/><h1>Dit vraagt onze aandacht.</h1><p>{message||'De generatie is veilig gestopt; er is niets dubbel gepubliceerd of afgeschreven.'} Mail <a className="support" href="mailto:info@landingsite.nl">info@landingsite.nl</a> en vermeld je betaalreferentie.</p></>:<><div className="orb"/><h1>We bouwen je pagina.</h1><p>Je workflow kan veilig hervatten als een externe dienst even hapert. Je mag dit venster sluiten; de oplevering gaat door.</p><div className="progress">{steps.map((step,index)=><div className={index<2?'done':index===2?'active':''} key={step}><span>{index<2?'✓':index===2?'●':'○'}</span>{step}</div>)}</div>{message&&<p>{message}</p>}</>}</div></main></>
}
