import type { DashboardData, Prospect, WebsiteAudit } from '@/lib/lead-engine/types'

const now = new Date()
const isoDaysAgo = (days: number) => new Date(now.getTime() - days * 86_400_000).toISOString()

function audit(input: {
  url: string
  design: number
  seo: number
  performance: number
  conversion: number
  trust: number
  responsive: boolean
  cta: boolean
  quote: boolean
  reviews: boolean
  outdated: boolean
}): WebsiteAudit {
  return {
    url: input.url,
    scores: { design: input.design, seo: input.seo, performance: input.performance, conversion: input.conversion, trust: input.trust },
    signals: {
      hasWebsite: true,
      isHttps: true,
      isResponsive: input.responsive,
      hasTitle: true,
      hasMetaDescription: false,
      hasH1: true,
      hasAboveFoldCta: input.cta,
      hasContactOption: true,
      hasQuoteForm: input.quote,
      hasAppointmentOption: false,
      hasWhatsapp: false,
      hasReviews: input.reviews,
      hasStructuredData: false,
      hasSitemap: false,
      hasRobotsTxt: true,
      hasAnalytics: false,
      hasGoogleTagManager: false,
      hasMetaPixel: false,
      hasCookieBanner: false,
      hasContactDetails: true,
      hasSocialLinks: true,
      copyrightYear: input.outdated ? 2019 : 2026,
      brokenLinks: input.outdated ? 2 : 0,
      totalLinksChecked: 8,
      responseTimeMs: input.performance < 50 ? 2_850 : 790,
      largestContentfulPaintMs: input.performance < 50 ? 5_100 : 1_900,
      cumulativeLayoutShift: 0.09,
      interactionToNextPaintMs: 240,
      pageSpeedScore: input.performance,
      looksOutdated: input.outdated,
      socialLinks: {},
      publicEmail: null,
      publicPhone: null,
    },
    summary: 'De grootste kansen liggen bij ontwerp en conversie. De mobiele homepage mist een duidelijke vervolgstap.',
    visualAssessment: input.outdated ? 'De visuele hiërarchie is vlak en de primaire actie valt onvoldoende op.' : null,
    auditedAt: isoDaysAgo(1),
  }
}

const paintAudit = audit({
  url: 'https://voorbeeld-schilder.nl', design: 34, seo: 48, performance: 39, conversion: 28, trust: 57,
  responsive: false, cta: false, quote: false, reviews: false, outdated: true,
})

export const DEMO_PROSPECTS: Prospect[] = [
  {
  id: 'demo-schildersbedrijf-janssen',
  source: 'KVK',
  sourceRecordId: '12345678:000012345678',
  kvkNumber: '12345678',
    establishmentNumber: '000012345678',
    companyName: 'Schildersbedrijf Janssen',
    tradeNames: ['Janssen Schilderwerken'],
    place: 'Veenendaal',
    postcode: '3905 AB',
    address: 'Voorbeeldstraat 12',
    legalForm: 'Eenmanszaak',
    registrationDate: '2025-12-04',
    active: true,
    employeeCount: 3,
    sbiCodes: [{ code: '4334', description: 'Schilderen en glaszetten', main: true }],
    websiteUrl: paintAudit.url,
    phone: '0318 12 34 56',
    email: 'info@voorbeeld-schilder.nl',
    googleRating: 4.8,
    googleReviewCount: 34,
    opportunityScore: 91,
    scoreClass: 'VERY_HOT',
    scoreBreakdown: [
      { key: 'outdated_website', label: 'Zeer slechte of verouderde website', points: 25, matched: true },
      { key: 'not_mobile_friendly', label: 'Niet mobielvriendelijk', points: 20, matched: true },
      { key: 'google_reviews_20', label: '20+ Google-reviews', points: 15, matched: true },
      { key: 'no_cta', label: 'Geen duidelijke CTA', points: 10, matched: true },
      { key: 'no_quote_or_booking', label: 'Geen offerte- of afspraakfunctie', points: 10, matched: true },
    ],
    pipelineStatus: 'HOT',
    recommendedChannel: 'INSTAGRAM',
    nextAction: 'Instagram-concept beoordelen',
    nextActionAt: isoDaysAgo(-1),
    estimatedValue: 899,
    urls: [
      { kind: 'WEBSITE', url: paintAudit.url, confidence: 0.96, source: 'Google Places' },
      { kind: 'GOOGLE_BUSINESS', url: 'https://maps.google.com/?cid=voorbeeld', confidence: 0.94, source: 'Google Places' },
      { kind: 'INSTAGRAM', url: 'https://instagram.com/', confidence: 0.92, source: 'Link op bedrijfswebsite' },
    ],
    audit: paintAudit,
    analysis: {
      whyInteresting: 'Sterke lokale reputatie met 34 Google-reviews, terwijl de website mobiel en conversietechnisch duidelijk achterblijft.',
      biggestProblem: 'Mobiele bezoekers zien geen heldere hoofdactie en kunnen geen offerte aanvragen.',
      recommendedImprovement: 'Een snelle mobiele homepage met projectfoto’s, reviewbewijs en een korte offerteaanvraag.',
      recommendedService: 'Pro website',
      openingLine: 'Jullie 34 Google-reviews vallen op; de mobiele website laat die sterke reputatie nog niet goed zien.',
    },
    drafts: [{
      id: 'draft-demo-1', channel: 'INSTAGRAM', status: 'READY', sendMode: 'MANUAL', profileUrl: 'https://instagram.com/', scheduledFor: null,
      body: 'Hoi! Jullie 34 Google-reviews vielen me op. Op mobiel is het nu alleen lastig om direct een offerte aan te vragen. Zal ik vrijblijvend laten zien hoe ik jullie homepage compacter en duidelijker zou maken?',
    }],
    notes: [{ id: 'note-demo-1', body: 'Eerst de mobiele homepage als demo uitwerken; reputatie is sterk genoeg voor een concrete insteek.', createdAt: isoDaysAgo(1) }],
    activities: [{ id: 'activity-demo-1', type: 'AUDIT_COMPLETED', outcome: null, occurredAt: isoDaysAgo(1), details: {} }],
    discoveredAt: isoDaysAgo(0),
    lastActivityAt: isoDaysAgo(1),
    suppressed: false,
  },
  {
  id: 'demo-de-groene-tuin',
  source: 'KVK',
  sourceRecordId: '23456789:000023456789',
  kvkNumber: '23456789',
    establishmentNumber: '000023456789',
    companyName: 'De Groene Tuin',
    tradeNames: [],
    place: 'Ede',
    postcode: '6711 AA',
    address: 'Markt 8',
    legalForm: 'Vennootschap onder firma',
    registrationDate: '2026-02-14',
    active: true,
    employeeCount: 2,
    sbiCodes: [{ code: '8130', description: 'Landschapsverzorging', main: true }],
    websiteUrl: null,
    phone: '0318 98 76 54',
    email: null,
    googleRating: 4.9,
    googleReviewCount: 27,
    opportunityScore: 90,
    scoreClass: 'VERY_HOT',
    scoreBreakdown: [
      { key: 'no_website', label: 'Geen website', points: 35, matched: true },
      { key: 'young_business', label: 'Bedrijf jonger dan 12 maanden', points: 20, matched: true },
      { key: 'active_instagram_bad_site', label: 'Actief Instagram en slechte/geen website', points: 20, matched: true },
      { key: 'google_reviews_20', label: '20+ Google-reviews', points: 15, matched: true },
    ],
    pipelineStatus: 'CONTACT_READY',
    recommendedChannel: 'INSTAGRAM',
    nextAction: 'Conceptbericht goedkeuren',
    nextActionAt: isoDaysAgo(-2),
    estimatedValue: 899,
    urls: [
      { kind: 'GOOGLE_BUSINESS', url: 'https://maps.google.com/?cid=voorbeeld2', confidence: 0.91, source: 'Google Places' },
      { kind: 'INSTAGRAM', url: 'https://instagram.com/', confidence: 0.88, source: 'Handmatig bevestigd: recente activiteit' },
    ],
    audit: null,
    analysis: {
      whyInteresting: 'Een jong lokaal bedrijf met 27 reviews en een zichtbaar socialprofiel, maar zonder eigen website.',
      biggestProblem: 'Potentiële klanten zijn afhankelijk van platformprofielen en vinden geen eigen overzicht van diensten en contact.',
      recommendedImprovement: 'Een compacte eigen website met diensten, werkgebied, reviews en een offerteaanvraag.',
      recommendedService: 'Starter website',
      openingLine: 'Jullie 27 reviews zijn een sterk begin; een eigen site kan dat vertrouwen veel beter omzetten in aanvragen.',
    },
    drafts: [{
      id: 'draft-demo-2', channel: 'INSTAGRAM', status: 'READY', sendMode: 'MANUAL', profileUrl: 'https://instagram.com/', scheduledFor: null,
      body: 'Hoi! Ik zag dat De Groene Tuin al 27 mooie Google-reviews heeft, maar nog geen eigen website. Zal ik vrijblijvend laten zien hoe een compacte homepage met werkfoto’s en offerteknop eruit kan zien?',
    }],
    notes: [],
    activities: [{ id: 'activity-demo-2', type: 'ENRICHMENT_COMPLETED', outcome: null, occurredAt: isoDaysAgo(0), details: {} }],
    discoveredAt: isoDaysAgo(0),
    lastActivityAt: isoDaysAgo(0),
    suppressed: false,
  },
  {
  id: 'demo-van-dijk-installatie',
  source: 'KVK',
  sourceRecordId: '34567890:000034567890',
  kvkNumber: '34567890',
    establishmentNumber: '000034567890',
    companyName: 'Van Dijk Installatie',
    tradeNames: [],
    place: 'Rhenen',
    postcode: '3911 BC',
    address: 'Utrechtsestraatweg 40',
    legalForm: 'Besloten vennootschap',
    registrationDate: '2018-05-20',
    active: true,
    employeeCount: 8,
    sbiCodes: [{ code: '4322', description: 'Installatie van sanitair en verwarming', main: true }],
    websiteUrl: 'https://voorbeeld-installatie.nl',
    phone: '0317 11 22 33',
    email: 'info@voorbeeld-installatie.nl',
    googleRating: 4.6,
    googleReviewCount: 19,
    opportunityScore: 78,
    scoreClass: 'HOT',
    scoreBreakdown: [
      { key: 'outdated_website', label: 'Zeer slechte of verouderde website', points: 25, matched: true },
      { key: 'not_mobile_friendly', label: 'Niet mobielvriendelijk', points: 20, matched: true },
      { key: 'no_cta', label: 'Geen duidelijke CTA', points: 10, matched: true },
      { key: 'no_quote_or_booking', label: 'Geen offerte- of afspraakfunctie', points: 10, matched: true },
    ],
    pipelineStatus: 'RESEARCHED',
    recommendedChannel: 'EMAIL',
    nextAction: 'Audit nalopen',
    nextActionAt: null,
    estimatedValue: 1299,
    urls: [{ kind: 'WEBSITE', url: 'https://voorbeeld-installatie.nl', confidence: 0.95, source: 'Google Places' }],
    audit: audit({ url: 'https://voorbeeld-installatie.nl', design: 48, seo: 51, performance: 46, conversion: 39, trust: 62, responsive: false, cta: false, quote: false, reviews: false, outdated: true }),
    analysis: null,
    drafts: [],
    notes: [],
    activities: [],
    discoveredAt: isoDaysAgo(2),
    lastActivityAt: isoDaysAgo(1),
    suppressed: false,
  },
]

export function demoDashboard(): DashboardData {
  return {
    metrics: {
      newToday: 2, veryHot: 2, hot: 1, draftsReady: 2, contactedToday: 3,
      replies: 4, appointments: 2, won: 1, conversionRate: 8.3, pipelineValue: 7_294, averageScore: 86,
    },
    hotLeads: DEMO_PROSPECTS,
    topPlaces: [{ label: 'Veenendaal', value: 12 }, { label: 'Ede', value: 9 }, { label: 'Rhenen', value: 6 }],
    topBranches: [{ label: 'Bouw & onderhoud', value: 14 }, { label: 'Zakelijke diensten', value: 8 }, { label: 'Persoonlijke verzorging', value: 6 }],
    bestChannel: 'Instagram · 14,8% reactie',
    bestOpening: 'Concrete observatie + lokale aanleiding',
    source: 'demo',
  }
}
