import type { Metadata } from 'next'
import Link from 'next/link'
import { pricingConfig } from '@/config/pricing'
import { BUSINESS, BUSINESS_ADDRESS } from '@/lib/business'

export const metadata: Metadata = {
  title: 'Algemene voorwaarden bouw en Websitebeheer',
  description: 'Zakelijke voorwaarden voor landingspagina&apos;s en Websitebeheer van Landingsite.nl.',
  alternates: { canonical: '/algemene-voorwaarden' },
}

export default function TermsPage() {
  const { buildPackages, websiteManagement } = pricingConfig

  return (
    <main className="legal-page">
      <div className="container legal-shell">
        <Link href="/" className="legal-back">← Terug naar Landingsite.nl</Link>
        <h1>Algemene voorwaarden</h1>
        <p className="updated">Versie 7 augustus 2026 · uitsluitend voor zakelijke klanten</p>
        <div className="legal-content">
          <section><h2>1. Wie wij zijn</h2><p>{BUSINESS.brandName} is een handelsnaam van {BUSINESS.legalName}, gevestigd aan {BUSINESS_ADDRESS}, {BUSINESS.address.country}. KvK: {BUSINESS.chamberOfCommerceNumber}. Btw-id: {BUSINESS.vatId}. Je bereikt ons via <Link href={BUSINESS.contactPath}>het contactformulier</Link>. Deze voorwaarden gelden voor de eenmalige bouwopdracht, Websitebeheer en aanvullend overeengekomen werk.</p></section>
          <section><h2>2. Zakelijke overeenkomst</h2><p>Onze diensten zijn bedoeld voor ondernemers en organisaties die handelen in beroep of bedrijf. Bij de checkout bevestigt de klant dit en accepteert de klant deze voorwaarden. De overeenkomst voor het gekozen bouwpakket en Hosting &amp; Websitebeheer ontstaat na succesvolle bevestiging van de Stripe-checkout.</p></section>
          <section><h2>3. Bouwprijzen, eerste betaling en btw</h2><p>{buildPackages.starter.name} kost €{buildPackages.starter.oneTimePrice}, {buildPackages.pro.name} €{buildPackages.pro.oneTimePrice} en {buildPackages.premium.name} €{buildPackages.premium.oneTimePrice} eenmalig, telkens exclusief btw. Bij de start wordt daarnaast de eerste maand Hosting &amp; Websitebeheer van €{websiteManagement.monthlyPrice} exclusief btw afgerekend. De eerste betaling is daardoor respectievelijk €378, €578 of €978 exclusief btw. Daarna incasseert Stripe maandelijks €{websiteManagement.monthlyPrice} exclusief btw. Aanvullend werk en externe kosten worden vooraf apart aangeboden.</p></section>
          <section><h2>4. Hosting &amp; Websitebeheer</h2><p>Hosting &amp; Websitebeheer kost €{websiteManagement.monthlyPrice} per maand exclusief btw. De eerste maand staat op de eerste Stripe-factuur; daarna factureert Stripe maandelijks vooraf. Het pakket omvat managed hosting, SSL, back-ups, herstelmogelijkheden, beveiligings- en technische updates, monitoring, controle van het aanvraagformulier, ondersteuning per e-mail en maximaal {websiteManagement.includedChangeMinutes} minuten kleine wijzigingen per betaalmaand. Niet-gebruikte tijd vervalt en wordt niet opgespaard.</p></section>
          <section><h2>5. Afbakening kleine wijzigingen</h2><p>Kleine wijzigingen zijn aanpassingen binnen de bestaande website, zoals tekst wijzigen, een foto vervangen, openingstijden aanpassen of een knop veranderen. Nieuwe pagina’s, volledige nieuwe ontwerpen, uitgebreide functionaliteiten, koppelingen en grote tekstprojecten vallen niet binnen Websitebeheer en worden vooraf apart geoffreerd.</p></section>
          <section><h2>6. Looptijd, opzegging en overdracht</h2><p>Websitebeheer loopt voor onbepaalde tijd met perioden van één maand. De klant kan via de beveiligde klantlink of het <Link href={BUSINESS.contactPath}>contactformulier</Link> opzeggen tegen het einde van de lopende betaalperiode. Na beëindiging stoppen hosting, technisch beheer, wijzigingen en ondersteuning aan het einde van de betaalde periode. We spreken een redelijke overdracht van domeininstellingen en klantspecifieke content af; extra migratiewerk kan apart worden berekend. Partnercommissie die aan dit abonnement is gekoppeld stopt eveneens.</p></section>
          <section><h2>7. Betaling en mislukte incasso</h2><p>De klant zorgt voor een geldige betaalmethode en juiste factuurgegevens. Bij een mislukte Websitebeheer-incasso mag Stripe opnieuw proberen. Wij mogen beheer, wijzigingen, ondersteuning of publicatie na waarschuwing opschorten. Openstaande bedragen blijven verschuldigd. Redelijke buitengerechtelijke incassokosten en wettelijke handelsrente kunnen worden doorberekend voor zover de wet dit toestaat.</p></section>
          <section><h2>8. Eerste versie binnen 48 uur</h2><p>De termijn van 48 uur ziet op een eerste websiteversie. De termijn start pas na succesvolle betaling van de eenmalige bouwprijs én ontvangst van een complete, bruikbare intake. De termijn is een inspanningsdoel en geen fatale termijn. Ontbrekende input, late reacties, extra wensen, overmacht of storingen bij externe diensten kunnen de planning redelijkerwijs verlengen.</p></section>
          <section><h2>9. Pakketscope en correctierondes</h2><p>Starter omvat één landingspagina met maximaal ongeveer zeven inhoudelijke secties, één formulier en één gebundelde correctieronde. Pro omvat maximaal vier kernpagina’s, een uitgebreider formulier en twee gebundelde correctierondes. Premium omvat maximaal acht kernpagina’s, maximaal twee formulieren en drie gebundelde correctierondes. Een correctieronde is één gebundelde lijst met wijzigingen binnen de overeengekomen structuur en inhoud. De klant levert correcties verzameld en tijdig aan.</p><p>Webshops, ledenomgevingen, maatwerk-SaaS, complexe rekentools, meertaligheid, grote migraties, fotografie, brandingtrajecten, maatwerkdatabases, betaalde externe software en onbeperkte revisies zijn niet standaard inbegrepen. Nieuwe pagina’s, een nieuwe huisstijl, omvangrijke aanvullende copy, functies of koppelingen kunnen aanvullend werk zijn en worden vooraf geprijsd.</p></section>
          <section><h2>10. Hulpmiddelen en inhoudelijke controle</h2><p>We kunnen software gebruiken voor conceptcopy, structuur en analyse. Conceptuitvoer wordt binnen ons proces gecontroleerd, maar de klant controleert feitelijke, juridische en branchespecifieke claims vóór definitieve publicatie. Het gebruik van hulpmiddelen geeft geen recht op onbeperkte ontwikkeling of een bepaald bedrijfsresultaat.</p></section>
          <section><h2>11. Rechten en materiaal van de klant</h2><p>De klant garandeert dat aangeleverde teksten, foto’s, logo’s, reviews en persoonsgegevens rechtmatig mogen worden gebruikt. Na betaling mag de klant de klantspecifieke oplevering voor de eigen onderneming gebruiken. Onze generieke templates, systemen, workflows, componenten en knowhow blijven van ons of de betreffende licentiegever. Open-source en externe onderdelen blijven onder hun eigen licenties vallen.</p></section>
          <section><h2>12. Domein, Websitebeheer en externe diensten</h2><p>De klant blijft eigenaar van de eigen domeinnaam en houdt waar mogelijk toegang tot de registrar. Tijdens actief Websitebeheer gebruiken we hosting-, betaal-, database-, e-mail- en andere diensten van derden. We selecteren en beheren deze zorgvuldig, maar kunnen geen ononderbroken beschikbaarheid van externe infrastructuur garanderen.</p></section>
          <section><h2>13. Privacy en verwerkersrol</h2><p>Ons <Link href="/privacybeleid">privacybeleid</Link> beschrijft hoe we klantgegevens verwerken. Voor persoonsgegevens die bezoekers via een formulier op de website van de klant insturen, bepaalt de klant het doel van de verwerking en handelen wij in beginsel als verwerker voor hosting, doorgifte en technisch beheer. Op verzoek maken we passende verwerkersafspraken.</p></section>
          <section><h2>14. Geen resultaatgarantie</h2><p>We beloven een professionele uitvoering binnen de afgesproken scope, maar garanderen geen specifieke omzet, leads, conversie, advertentieresultaten of positie in zoekmachines. Die resultaten hangen mede af van aanbod, markt, verkeer, budget en opvolging door de klant.</p></section>
          <section><h2>15. Aansprakelijkheid</h2><p>De klant meldt fouten zo snel mogelijk en geeft ons een redelijke kans om ze te herstellen. Voor zover wettelijk toegestaan is onze totale aansprakelijkheid beperkt tot de betaalde bouwprijs plus maximaal drie maanden Websitebeheer voorafgaand aan het voorval. We zijn niet aansprakelijk voor indirecte schade, gemiste winst, onjuiste klantinput of uitval van externe diensten. Deze beperkingen gelden niet bij opzet of bewuste roekeloosheid van onze bedrijfsleiding en laten dwingend recht onverlet.</p></section>
          <section><h2>16. Wijziging van dienst of voorwaarden</h2><p>We mogen de dienst, pakketinhoud, prijs of voorwaarden aanpassen wanneer bedrijfsvoering, beveiliging, wetgeving of leveranciers dit redelijkerwijs vraagt. Bij een wezenlijke wijziging voor een lopend abonnement informeren we de klant minimaal één maand vooraf. De klant kan dan opzeggen vóór de wijziging ingaat.</p></section>
          <section><h2>17. Klachten en recht</h2><p>Stuur een concrete klacht via <Link href={BUSINESS.contactPath}>het contactformulier</Link>. We proberen binnen tien werkdagen inhoudelijk te reageren. Nederlands recht is van toepassing. Geschillen worden voorgelegd aan de bevoegde Nederlandse rechter, voor zover dwingend recht niet anders bepaalt.</p></section>
        </div>
      </div>
    </main>
  )
}
